name: CI/CD Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main, master]

permissions:
  contents: write
  deployments: write

concurrency:
  group: pipeline-${{ github.ref }}
  cancel-in-progress: false

jobs:
  prepare-version:
    runs-on: ubuntu-latest
    outputs:
      next_tag: ${{ steps.bump.outputs.next_tag }}
      release_notes: ${{ steps.notes.outputs.notes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Bump semantic version
        id: bump
        run: npm run version:bump

      - name: Generate release notes
        id: notes
        env:
          RELEASE_ENV: base
          RELEASE_VERSION: ${{ steps.bump.outputs.next_tag }}
        run: npm run version:notes

      - name: Upload bumped package metadata
        uses: actions/upload-artifact@v4
        with:
          name: bumped-package
          path: |
            package.json
            package-lock.json

  build:
    needs: prepare-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download bumped package metadata
        uses: actions/download-artifact@v4
        with:
          name: bumped-package
          path: bumped-package

      - name: Apply bumped package metadata
        run: |
          mv bumped-package/package.json package.json
          mv bumped-package/package-lock.json package-lock.json
          rm -rf bumped-package

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test
      - name: Install & Build (Bun-first with fallbacks)
        run: |
          bun install
          npm run build || bun run build || bunx @vercel/ncc build src/index.js --license licenses.txt
          zip -r build.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip

  deploy-dev:
    needs:
      - build
      - prepare-version
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Release Dev
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.prepare-version.outputs.next_tag }}
          NOTE: ${{ needs.prepare-version.outputs.release_notes }}
        run: |
          TAG_WITH_ENV="${TAG}-dev"
          NOTE_WITH_ENV="${NOTE}"$'\n'"Environment: dev"
          gh release delete "$TAG_WITH_ENV" -y --repo "$GITHUB_REPOSITORY" || true
          gh api -X DELETE "repos/$GITHUB_REPOSITORY/git/refs/tags/$TAG_WITH_ENV" || true
          gh release create "$TAG_WITH_ENV" build.zip --notes "$NOTE_WITH_ENV" --repo "$GITHUB_REPOSITORY"

  deploy-staging:
    needs:
      - deploy-dev
      - prepare-version
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Release Staging
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.prepare-version.outputs.next_tag }}
          NOTE: ${{ needs.prepare-version.outputs.release_notes }}
        run: |
          TAG_WITH_ENV="${TAG}-staging"
          NOTE_WITH_ENV="${NOTE}"$'\n'"Environment: staging"
          gh release delete "$TAG_WITH_ENV" -y --repo "$GITHUB_REPOSITORY" || true
          gh api -X DELETE "repos/$GITHUB_REPOSITORY/git/refs/tags/$TAG_WITH_ENV" || true
          gh release create "$TAG_WITH_ENV" build.zip --notes "$NOTE_WITH_ENV" --repo "$GITHUB_REPOSITORY"

  deploy-production:
    needs:
      - deploy-staging
      - prepare-version
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Release Production
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.prepare-version.outputs.next_tag }}
          NOTE: ${{ needs.prepare-version.outputs.release_notes }}
        run: |
          TAG_WITH_ENV="${TAG}"
          NOTE_WITH_ENV="${NOTE}"$'\n'"Environment: production"
          gh release delete "$TAG_WITH_ENV" -y --repo "$GITHUB_REPOSITORY" || true
          gh api -X DELETE "repos/$GITHUB_REPOSITORY/git/refs/tags/$TAG_WITH_ENV" || true
          gh release create "$TAG_WITH_ENV" build.zip --notes "$NOTE_WITH_ENV" --repo "$GITHUB_REPOSITORY"
